### ISSUE TITLE
Indicate Missing Resource Cards

### ISSUE THREAD

**Issue by seojoon-y** [colonistio/design#131]
## Summary
When playing colonist.io, I always have to think about which resource card I'm missing to build a settlement, road, etc... It would be super useful to indicate which resource cards you already have, and which you are missing.
<img width="237" alt="as" src="https://user-images.githubusercontent.com/83441512/184070260-61d6dbb2-3c34-4e18-b4fb-a14a7c8dba70.png">

I propose a minimalistic design of simply showing a green check-mark on top of the cards you have. Also, I advise against putting a red cross on top of missing cards. This is because a red cross may indicate "disabled" or "blocked" and can potentially confuse the players. It would be redundant too.

## Proposed design:

<img width="1433" alt="img" src="https://user-images.githubusercontent.com/83441512/184069833-af601563-d262-4090-8061-ee218fd157e5.png">

## Related links

- Icon taken from NounProject ( I have NunProject subscription ): https://thenounproject.com/icon/check-1813701/
- Color: #71D358
![check](https://user-images.githubusercontent.com/83441512/184069907-c385f8b6-9e09-49a7-bf49-fa084e2c47c6.png)

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by demiculus** [comment]
I think this is a submission rather than a design issue to be designed later on. So I'll comment on it as a submission.

1. The check icon, we have plenty of our own inside the assets file. Its good practice to continue using those. Our icons are not coherent. We'll eventually have an art style guide and make them all coherent. But sticking to the current assets decreases introducing new styles.
2. Check is an idea, check on card is another, hollowing out is another. In submissions you should show the other other designs you tried and explain why you picked the one you picked. 
3. I think its not clear what these checks are, might confuse players.

You can 

1. Create a new submission with a bunch of ideas
2. Create a design issue and leave it for later

**Comment by goktugyil** [comment]
2. Cross icon on card + hollow is another idea
