### ISSUE TITLE
Profile Revamp - Overview - Showing Game Modes (Studies)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#163]
## Summary
Following the discussions at the team meeting and comments on the previous submission, this submission shows the screens + scenarios of the possible design. Where we show all game modes in the overview tab

The research was done in the previous submission: https://github.com/colonistio/design/issues/157

### Ranked Games Prioritized
![image](https://user-images.githubusercontent.com/90673012/188465749-965096bf-f80e-412e-aef7-9359aa842a6d.png)

- based on Juan's idea. Removed the title of the game mode since we already have the image, added games played instead like in `vs Bots`
- When the game mode icon is hovered, it will show what game mode it is. 
- Lobby Games: I made it scrollable since like Ranked, there's a bunch of game modes people can play in the Lobby
- Change the orientation of how MMR progress is presented based on the design here: https://discord.com/channels/605233308577562643/790772223358402571/1015368484684832998

### All Game Types Equal

![Overview  Tab - Showing All Game Modes](https://user-images.githubusercontent.com/90673012/188466685-c52507f5-42f7-489c-9fa5-4b650d7a47ca.gif)

- Format follows what we're using for the items presented on our store page.
- Vs Bots and Ranked: games mode icons will show either a bot icon or the player's current division beside them. 
- Vs Bots with different game modes can be removed since it's not in development yet. 

### Lobby Games Prioritized
![image](https://user-images.githubusercontent.com/90673012/188468983-b803f4cc-1480-424d-97ac-8efa3d96f80d.png)

- Adds `vs Bot` Games in the Lobby games section
- Bigger space compared to `Ranked Mode Prioritized` for the scrollable part
- Players can go to the `Ranked` tab for more info instead of showing everything in the overview tab

## Related Submissions

- https://github.com/colonistio/design/issues/157
- https://github.com/colonistio/design/issues/120

## Related links

- https://github.com/colonistio/design/issues/139
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by JuanRoman77** [comment]
I don't want to prioritize Lobby games:
- It drives people away from Ranked (and Memberships).
- There are too many game modes and settings possibilities, making the section extremely clogged.

Iterate on this design https://i.imgur.com/sWCBaUR.png, but only change the MMR progress bar. That still doesn't look good.
Also it wasn't my idea to remove the game mode names. I was against it, please add them back. The images are not clear representations of each of the game modes, they were just place holders that were never updated (the castle has almost nothing to do with C&K, the pirate ship is poorly designed, the base board doesn't mean 4P since many other game modes are played on it, etc.).

Also:
- No scrolling (unless mobile or really small screens)
- Change the **-** in the Membership section to a green Become a Member link
