### ISSUE TITLE
Matchmaking Optimization Submission #1 - Design Studies

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#168]
## Summary
Omar did a couple of tests here: https://github.com/colonistio/katan/issues/8048 , https://github.com/colonistio/katan/issues/8130 

and came up with this conclusions:
- Highest priority to optimize matchmaking is to make lobby harder to access than matchmaking games.
- Next comes making matchmaking easier to access in general.
- Having "Play" inside CTAs isn't worth optimizing at the moment, might explore later with improved designs.

I polished some of the ABTests that produced relevant results and show it here.

## Studies

Left side is from ABtest - right Side is the revised

### Large MM Buttons
![image](https://user-images.githubusercontent.com/90673012/189774058-5069a08d-96e2-42d3-a37a-b0639c800372.png)

- Added info icon for game settings
- Added division icon for player rank on ranked games
- Base Map BG for all game modes

### Small MM Buttons with Profile / Summary
![image](https://user-images.githubusercontent.com/90673012/189774125-c2727cad-259a-44bb-8a92-64d4b9b257d9.png)

- Removed Lobby/Spectate
- Added MM C&K and SF with `Coming Soon!`
- Added Tabs for Player Profile

### Lobby inside Play CTA
![image](https://user-images.githubusercontent.com/90673012/189775163-688ea2ba-a62a-43f9-b021-a03dec32988d.png)

- Full summary for profile
- Adds Lobby inside Play CTA (not shown here) we can also move this in the header

### Remove CTAs - Put Lobby in Header
![image](https://user-images.githubusercontent.com/90673012/189774734-83aacc71-9cb6-47a4-b406-1e4aee265a18.png)

### Lobby inside Play CTA
![image](https://user-images.githubusercontent.com/90673012/189774166-4d86c529-4182-4cda-90cf-b56f919afb0a.png)

### Remove CTAs - Put Lobby in Header (Idea)
![image](https://user-images.githubusercontent.com/90673012/189774209-8d6d7ba9-160c-4207-bd86-872374843f90.png)

- Not in ABTest
- Removes Lobby and CTAs in the header and replace them with MM cards
- Bigger screen to play around but fewer store ad space

## Related links

- https://github.com/colonistio/katan/issues/8130
- https://github.com/colonistio/design/issues/165

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus @omarhurani 

I can prototype the best one here with animation/hover states and create an implementation issue.

**Comment by JuanRoman77** [comment]
These should've been done from scratch, not based on Omar's designs. The UI/UX is terrible.
- Tons of containers of different type, size, colors, positions
- Huge visual load
- No hierarchy
- Not clear where to click on, what each of them do
- Cards don't look like buttons
- History doesn't go in the lobby
- Lobby inside Play button doesn't make sense

@demiculus we need a clear outline for this project before starting with the designs.

**Comment by omarhurani** [comment]
@JuanRoman77 This is why you don't want to miss meetings lol

Design-wise not much input from my side, I don't have the taste for it (yet). I don't think I mentioned this explicity but I took lot of these ideas from [Chess.com](https://www.chess.com/), you can look into it to see if things can be done better or if the design suits us to begin with. Note that it has a different UI for guests and signed-in accounts.

> * Not clear where to click on, what each of them do

ABTest proves otherwise?

> * Cards don't look like buttons

Same ^

> * History doesn't go in the lobby

Well the idea is for it not to be a lobby, it is a home page.

**Comment by JuanRoman77** [comment]
> @JuanRoman77 This is why you don't want to miss meetings lol
> 
> Design-wise not much input from my side, I don't have the taste for it (yet). I don't think I mentioned this explicity but I took lot of these ideas from [Chess.com](https://www.chess.com/), you can look into it to see if things can be done better or if the design suits us to begin with. Note that it has a different UI for guests and signed-in accounts.
> 
> > * Not clear where to click on, what each of them do
> 
> ABTest proves otherwise?

It doesn't, you don't know how long it took new users to decide what to click

> > * Cards don't look like buttons
> 
> Same ^

Same ^

> > * History doesn't go in the lobby
> 
> Well the idea is for it not to be a lobby, it is a home page.

Typo, I meant homepage


Your designs didn't need to be good, Omar. Copying from other page worked because you were trying to prove that removing the lobby would increase Ranked traffic. That was verified. But it doesn't mean that we should just change the current UI to what was live in the tests. It means we should redesign the homepage to prioritize Ranked, but in the most efficient way possible, minding UI and UX. Hence my previous comment.

**Comment by samgawaran** [comment]
I agree that the button design/layout could be better, 

but for the overall design, I think I'll need more specific requirements like _would we need to adjust the landing page as well?_

but here are some of it:

1. Can I remove some store ad spaces
2. Move the MM cards at the old space of the Lobby or replace it with some profile stats? other stuff I could find on a research?
3. How big of a change are we planning for the homepage

@demiculus let me know here. Thanks

> It doesn't, you don't know how long it took new users to decide what to click

I remembered there's an analytics tool that can track this. I don't remember the name though, something like Rocket

**Comment by demiculus** [comment]
## Good Questions

Good questions, when stuck, asking for insightful questions helps us move forward.

> Can I remove some store ad spaces

Yes, we can shuffle anything anywhere
> Move the MM cards at the old space of the Lobby or replace it with some profile stats? other stuff I could find on a research?

Better to replace them with something.

> How big of a change are we planning for the homepage

Ideally not a huge change, our goal is not to create ideal main page. Our goal is to reap the benefits of the research. Then do more research. 

## Notes

1. We should have a name for this page. I suggest Main Page.
  - Landing Page -> is the page we land on
  - Lobby -> obvious what it is
  - Room -> obvious what it is
  - Home or Home Page-> all of these pages combined we call it Home Page (check out EntryHomepage)
  - Main Page -> this page
2. We can not design the perfect MainPage. We shall design according to good principles and iterate from there.
3. Majority of the players play 1 or 2 modes. They do not play many different modes. It doesn't make sense to have a design like this: https://i.imgur.com/wUB8n4d.jpg, since 3 out of 4 of those will be unused 80% of the time and 2 out 4 will be unused the rest of the time.

## Moving Forward

1. Keep the current layout on the left side and the right side
2. In the center put overview in a nice way (make it something easy) we'll experiment with it over time
3. for "Enter Lobby" do a few things
  A. Add it under the main CTA as a text button (maybe italic)
  B. Add it as an option inside of "Play"
  C. Add it to the Header
  D. Any other position you want to add it
