### ISSUE TITLE
Premium Rooms - Iteration 2 (Screens + Scenarios)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#198]
## Summary
New iteration for the "Upgrade Room" based from the feedback on the previous iteration: https://github.com/colonistio/design/issues/196#issuecomment-1282293834

### Screens
![image](https://user-images.githubusercontent.com/90673012/197154314-3ff66761-687f-4f9c-ac9b-7f9ed6599f9c.png)
- Made the CTA use $color-cta-main when room is upgraded to indicate its "unlocked" status

### Mobile Screens
![image](https://user-images.githubusercontent.com/90673012/197160626-3e579405-8ffb-4c1e-8d77-450278d520ad.png)

### Lock Icon
![image](https://user-images.githubusercontent.com/90673012/197151996-2cd0f9ed-90ca-46cf-8ddf-6c1cc8ac58ea.png)

- created new lock icons based on the given feedback. A new version where its semi unlock to indicate they can still change modes,maps that they owned and an unlocked version where they can access everything.
- We can also use a single lock icon (semi-unlock) so it won't change too much

### Popup
![image](https://user-images.githubusercontent.com/90673012/197152726-570d34cb-a7f8-4aae-a9ad-57c4a3c0fccc.png)

- popup design and copy. The popup title is still not finalized. can be adjusted on implementation issue

### Default Room
![image](https://user-images.githubusercontent.com/90673012/197155395-bcef4e26-f74f-490e-b8b8-bb3ce54bb0fe.png)

- When hovering on the lock icon. `Unlock all (subject) for 1 game when you upgrade this room`
- For mobile, players need to click the locked icon to show the infobox

### Upgraded Room
![image](https://user-images.githubusercontent.com/90673012/197155960-d1b877ec-7807-48d7-89b4-3eac0ec6b75a.png)

- change all cta colors to `$color-cta-main` beside the upgraded room
- All dropdown options will be accessible even if the player(s) doesn't own a specific map/expansion/color

## Related Submissions
- https://github.com/colonistio/design/issues/196

## Related Links

- https://github.com/colonistio/design/issues/195

## Submission Checklist
- [x] other stuff written in the checklist was done on the previous iteration [here](https://github.com/colonistio/design/issues/196)
- [x] how other games show their lock icons?
_- same with the checkout page, they are showing it on the left side before the word._ 
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @alexcoleman7

**Comment by alexcoleman7** [comment]
Thanks, Sam! I have a few comments.

The items in the pop ups should say All Maps, All Expansions, and All Colors. I think it helps send the message better. 

I like the unlocked icon but I think the locked icon just looks like it's unlocked too. I think you only realize it's more closed once you see the other one. Let's just revert to the fully locked icon.

The map and expansion containers already have a message in brackets and we need to keep these. I think the lock with the tooltip is enough otherwise it gets too crowded. Discard limit and VP to win are not premium items so they don't need a lock, number of players can keep the lock.

The dropdowns are created by each player's individual OS and are an element that we can't edit just yet. So we can't show the text in grey if they don't own it. For now if they players click on something they don't own they get this message:
<img width="207" alt="image" src="https://user-images.githubusercontent.com/60288677/198409422-c110f0b7-0f69-484e-926e-c1a3e57abc8c.png">
We just need to add at the end 'Visit the Store or upgrade to a Premium Room'. If the Premium Rooms are successful we should look into making a tailored dropdown.

**Comment by samgawaran** [comment]
Hey Alex! thanks for the straightforward comments, I did the changes in a new iteration here: https://github.com/colonistio/design/issues/202

closing this submission issue now.
