### ISSUE TITLE
Subdivision Rankings - Edits (Screens and Scenarios)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#249]
## Summary
The design for the subdivision icons are still bulky. This submission compiles the feedback and actionable items for this issue.

reserach is done here: https://github.com/colonistio/design/issues/248

## Design Comparison
![image](https://user-images.githubusercontent.com/90673012/209612953-8ecf5a22-b046-4eb0-88ac-60bedbad24b9.png)

- The design from the previous submission uses `Gilroy Extra-bold` its thinner than the original version but some feedbacks says its still bulky. New design uses a thinner version of `Gilroy Bold` called Semibold so its distinguishable to our other bold texts
- this new design is thinner of around 30% compared to the previous version

### Desktop
![image](https://user-images.githubusercontent.com/90673012/209614248-bde35720-b1be-487a-9e1b-44f2b115e4c5.png)

- Applied Jeffs suggestion on this issue: https://github.com/colonistio/katan/issues/9358
- for `End Game Screen` using the same orientation with Leaderboards and Profile Ranked wouldn't work due to the size of the icons. look here for what it would look like: https://prnt.sc/63Xr02l1bnti I suggest just using the plain text for simplicity

### Mobile
![image](https://user-images.githubusercontent.com/90673012/209614282-45fc8faf-f255-4fd9-a1f8-f84abe41dc77.png)
- Mobile versions of its desktop counterparts

## Related Submissions
- https://github.com/colonistio/design/issues/248

## Related Link: 
- https://drive.google.com/drive/u/0/folders/102RyzIvoWBb3y1_IRCYJxb1GCP2Adzzp

## Submission Checklist
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77 @JeffdEon

**Comment by JeffdEon** [comment]
Could you crop the images so that the text is wrapped evenly? All the images have a different centre. 
<img width="1557" alt="Screenshot 2022-12-27 at 7 42 32 AM" src="https://user-images.githubusercontent.com/58959537/209668579-907bfb6d-fed3-41d7-bd64-60ef33e7b060.png">

Could you keep the version you already shared and provide 2 slightly different versions? 

- 1 version where all images are the same size (like they are now) but the text is entered)
- 1 version where all images have different width (all same height) but are cropped to wrap the text so that the text is centered.

**Comment by samgawaran** [comment]
Created 2 more versions:
Textwrap (same height but width is cropped on borders of each number)
https://drive.google.com/drive/folders/1uleM1faPoAWuUT0ko1ozJzVADmAvMeF2?usp=sharing

Centered (same with left aligned but centered)
https://drive.google.com/drive/folders/10jVWMIAmIjRIexumPZbXDrKmkqVb2E6I?usp=sharing

___________
Didn't add the centered version initially since my suggested implementation in the end game screen should just use the basic text style to reduce the number of icons. but the file size is very small (only bytes) so attached it here as well.

**Comment by JeffdEon** [comment]
great! this worked, at what point do we close design issues?

**Comment by goktugyil** [comment]
Why are we going with the thinner option again?

Here:

![](https://i.ytimg.com/vi/x-uhBwdAXTI/maxresdefault.jpg)


- The gold color looks better than silver color
- Thick with large space between (captain) looks better

But generally the problem with romen numerals is, the higher the number, the better it looks like, while we want to give players the opposite perspective.

========

![](https://liquipedia.net/commons/images/thumb/4/4c/SC2_League_Tiers.jpg/410px-SC2_League_Tiers.jpg)


Here, Because numbers are written in latin number, one does not look better than the other and it conveys the message properly

**Comment by demiculus** [comment]
@samgawaran it still looks ugly, try to make it look pretty some ideas
- position (might be further or horizontally centered)
- size (might be smaller or bigger, probably smaller)
- font, this plain bold text obviously doesn't fit with the icons, it might be italic, normal weight, semi bold, or completely different font
