### ISSUE TITLE
Mobile App - P1: Homepage, Menu & Popups 

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#253]
## Summary
Got some feedback from last team meeting and tried out a bunch of different studies for our Homepage. I also included the popups as its generally used in the homepage as well

All designs are moddable to one another. Cherrypick on a promising component and I'll merge it with the other from the other studies

### Current Portrait Version in Mobile Browser
![image](https://user-images.githubusercontent.com/90673012/210626284-214bf39d-dc37-45ad-b69a-713c8b7f27a9.png)

### Homepage
- Smallest font size used is 14px. will expound on this on a separate issue
- Designed the following studies with putting ads in mind. It can be remove in any case to free space up or if we use video ads for mobile

![image](https://user-images.githubusercontent.com/90673012/210625456-5fda9e44-b5ba-4761-bd6d-335bb3275aa3.png)
`A` - simplified the study from [last week](https://prnt.sc/UWYLS8ibcG3l) Added everything besides the social counter thats inside the homepage. Profile stats, separate buttons for Create and Play vs Bots. Used flat colors but retained strokes and dropshadows on the CTAs
`B` - Different footer, adding Menu to remove the menu icon on top. Game mode selection is besides the play now instead of on-top. Added new _battle pass_ membership image. used a ticket shape icon so its different on our CTAs
`C` - direct translation of our website to mobile app. `Play` will have unranked games inside. Game Mode popups will have a seperate issue to discuss is further

### Popups
- All color used in the popups are inside the codebase
- didn't try to do an entirely different version, wanna nail the UX first
- uploaded a version with a scroller and one without
- Added an X button on all versions, almost all popups on Mobile has an X button somewhere since they don't have hover states

![image](https://user-images.githubusercontent.com/90673012/210632429-af8bc81c-b261-456f-9037-fde16658a7a7.png)

`A` - Current implementation in the desktop browser. Left aligned, same color scheme
`B` - Updated color, uses a lighter blue color we're using. Centered for short popups while for long popups we can retain left aligned since its easier to read
`C` - Form type. similar with Risk, We can show it either on top or at the bottom

### Menu
- Added all of the pages we have in our footer.
- I didn't use social media icons in one of the studies. Games that I checked doesn't have that button, instead they only show social media buttons that they can link their account into.

![image](https://user-images.githubusercontent.com/90673012/210629965-f8a50fd9-c8a4-49d7-8ce4-5a125d6f0dc9.png)
`A` - Form style Menu, clicking on that button will popup a selection of pages from our desktop footer
`B` - Side Nav, works with the menu icon on top. I can adjust the size to make it fit with the menu on the footer, didn't include social media buttons. Tested out showing a `New` tag if we have new updates. otherwise we can use the red blip for them
`C` - Full screen. Easiest implementation for an MVP. 

_______________________________________________

### Other Screens
**Animation for Promoted Items**
![Loom _ Free Screen  Video Recording Software _ Loom - 5 January 2023](https://user-images.githubusercontent.com/90673012/210633752-0c0dcf74-486d-4321-96ce-ab2baeec9509.gif)

- we can show something like this for assets we want to highlight. I'll focus on this on another submission later on

**Loading Screen Login**
![image](https://user-images.githubusercontent.com/90673012/210634208-924a9971-11b9-4e9d-b8a5-1512decb169e.png)
- followed how other games show their Guest CTA. retained the copy we are using for our account logins. But more games use `Continue with (account)` instead of `Login with (account)`

## Related Links

- https://github.com/colonistio/design/issues/226

## Submission Checklist
- [x] I experimented on what we could do on our original assets first before creating an entirely new design that we may not use.
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@JuanRoman77 @demiculus

**Comment by JuanRoman77** [comment]
I'd start by removing these. @demiculus ?
![image](https://user-images.githubusercontent.com/73320460/210638063-76b8c390-334e-4a05-aea9-2078c4f53453.png)

**Comment by samgawaran** [comment]
> It feels clogged, so I'd start by removing these

I agree to some extent for the profile stats here. though a possible point of revenue in the homepage will be lost if we remove the coin top-up at the top. Its also common to show coin top-ups on all mobile apps that I played so it should be there.

for the profile stats, I remembered @SimonH321 suggested removing a column or statline in that area. maybe we could do that here? `Total Games` and `Win%` are more important than `Points` in my opinion, we can also apply these changes in our desktop homepage in the long run.

**Comment by demiculus** [comment]
Nice clean work 👍

I'm going to get some UX feedback from seniors over the next few days. For now, what I think

1. We don't have battlepass -> don't add stuff we don't have https://i.imgur.com/T3bFrH9.jpg
2. Go with 5 option bottom https://i.imgur.com/4u8Jyf8.jpg
3. Button styles (shades etc..), colonist.io is between B & C. https://i.imgur.com/nak3FBE.jpg do Colonist.io style
  3a. If you want to suggest a style, create a separate issue and show mobile page and web home page how it looks
4. This is most important part. Generate me 10 different ideas of only this section https://i.imgur.com/9dS6pkC.jpg
  Goals: 
    - First time users can easily see what modes there are (Bot, Ranked, Room)
    - First time user can easily play the mode they want
    - Senior users are prompted to play the modes we want them to play. We want to push them towards 1v1 (for better retention) or C&K (for better monetization)
5. Definitely no. Doesn't belong in the home page. Takes important real estate. https://i.imgur.com/RkMh7ZI.png
6. These 2 are good stuff but too much crowd, use the top one for now https://i.imgur.com/hvhcOcH.png
7. Use the middle one https://i.imgur.com/HUA6pse.jpg
8. Remove the ad
9. Go with first popup https://i.imgur.com/Eq829Uv.png
  9a. if you're suggesting color change as in the middle option, make sure to suggest in a new issue having both web & mobile screenshots
10. Menu, go with the first one, should be fullscreen page instead of a drawer https://i.imgur.com/TpBEEOK.png, it doent need a X to close. It should use the same background and colors as the main page
11. Re suggest the animation in 3 months
12. Reduce complexity https://i.imgur.com/1q6DY18.png wtf are the people there? :D also the circles 
13. https://i.imgur.com/1q6DY18.png Make sure the login buttons go towards google, apple guidelines. Check the logos of Google as well make sure its okay. 
14. Remove v149 from both pages
15. Make this book https://i.imgur.com/70Ttybb.png dont change such stuff maybe also try a text version of the icons but not like option C thats just bad.
