### ISSUE TITLE
Subdivision Icons - Iteration #3

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#255]
## Summary
Did some changes and revisited some designs based from the feedbacks given on the thread here: https://github.com/colonistio/design/issues/249

Adjusted the size, looks of the icons and color for this submission

### Comparison
![image](https://user-images.githubusercontent.com/90673012/211034419-b9224f21-0ea4-4f73-8d5d-c6bd753232cc.png)

- Current version uses our Gilroy font style, While using Semibold to differentiate it with the others. 
- https://github.com/colonistio/design/issues/249#issuecomment-1367305217 from this, I decided to use a similar font with our logo fontstyle but thinner and smaller. comparison here: https://prnt.sc/cilz0CDtaLBs
- Did a couple of versions where we use gold color as Goku suggested. Though I'd still recommend white since we use white a lot more on the website
- All of the icons in the new version are centered. I realize seeing the icons left aligned make it look clogged
- gold icons uses the color we're using with our coins

### White Version (Recommended)
![image](https://user-images.githubusercontent.com/90673012/211035493-c72c8e56-ae5f-4612-b319-453fb9f016c7.png)
- followed all agreed layouts from previous iterations.

### Gold Version
![image](https://user-images.githubusercontent.com/90673012/211035538-f2da9267-8f66-4982-8a6b-51f938e5f869.png)
- gold version counterpart of the white version

### Mobile Web
![image](https://user-images.githubusercontent.com/90673012/211036257-e0ade7a1-e553-4ca1-9023-9b2f5b50ee27.png)
- mobile counterparts of the white version. can be adjusted to gold if its the one we're choosing

## Related Submissions
- https://github.com/colonistio/design/issues/249

## Related Link:
- GDrive: https://drive.google.com/drive/folders/102RyzIvoWBb3y1_IRCYJxb1GCP2Adzzp?usp=sharing

## Submission Checklist
- [x] I considered the feedback given on the previous iterations and checked out possible solutions on what I could do for all parties involved
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@JuanRoman77 @JeffdEon @demiculus

**Comment by JuanRoman77** [comment]
- Not gold, it's confusing. We have a bunch of different colors already. White is good.
- New font fits the style slightly better than Gilroy, but is too bulky. Might work if it was thinner. Can you try that?

**Comment by JeffdEon** [comment]
I would agree. White is better. Once final assets are ready just update them directly in code

**Comment by woodifred** [comment]
I like that the typeface you're using has enough unique character that it's differentiated from the other numbers all over the screen. It needs that level of personality to work as an icon/badge system. The trade-off is it feels a little chunky. In this case, I think it would be better to be a little too bold than a little too thin. 

The yellow/gold colour does have more contrast on the blue background, but it's confusing if the use of gold is not 1:1 with other icon systems in the game (example below), so I would go with white too.

<img width="187" alt="Screen Shot 2023-01-12 at 10 58 14 PM" src="https://user-images.githubusercontent.com/51459338/212234061-b971d223-1a89-43b3-b8aa-706cf06faa2f.png">

**Comment by JeffdEon** [comment]
tell me when ready to implement and final decision is made.

**Comment by JuanRoman77** [comment]
Still too bulky. Maybe a thiner version of that font? Or just keep the current implementation, close this issue, and move on.

**Comment by demiculus** [comment]
Guys when giving feedback to designs 

1. Make sure to give feedback in `principles` instead of `It feels`, `I like`, `I think`
  1a. Ensures we all gain new principle thinking
2. Break down the problem to its components 
3. Each of your comment should finalize one decision so there is no room for further discussion

----

## Decision Importance

This isn't going to make or break the game. So we'll decide fast and move on.

## Color -> White

Inconsistency - We don't have the gold color anywhere on the site, color should be consistent. 
Consistency - I would go with a shade of blue or white

For simplicity go with `White` 

## Style

<img width="301" alt="image" src="https://user-images.githubusercontent.com/6215305/212457591-e1e6e2d5-20ef-47d2-b3dd-6a28b03623b3.png">

Take a close look at the icon & the number. Look at the 
- curves
- border
- shadow
- margins https://i.imgur.com/hcywXaM.png
- font is slanted, icon is straight 
- lighting
.. 

Overall the 2 pieces are as unrelated as my bedsheets and a pilates ball. 

## Icon/Badge vs Text

As James mentioned, previous version looks like a text. This version looks like a badge. Go with a badge. 

----

Result: Go with White Badge, create implementation issue and close this.
