### ISSUE TITLE
Colonist Discord Loading Screen (Studies)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#320]
## Goals
Create a loading screen for Colonist Discord

### Progress Bar (Recommended)
![Study 1](https://user-images.githubusercontent.com/90673012/230563123-11dffbfc-ffe9-4e20-84a5-0f3de8a3e80b.gif)
![Study 2](https://user-images.githubusercontent.com/90673012/230563133-b8588eb1-1f2d-4dcd-8a35-e5548d862be4.gif)

- We can either use the new mobile app logo or the current logo on the Desktop. 
- I'm recommending this solution since we already use this in the mobile app

### Circular Loading
Uses exported GIF
![Study 3](https://user-images.githubusercontent.com/90673012/230563132-9156e290-cdad-4b81-9e6c-74f1984bea76.gif)
Uses smart animate in Figma
![Study 4](https://user-images.githubusercontent.com/90673012/230563136-dbb2593c-d3af-4fe8-aaf1-add5b9a5cdb7.gif)

- same with Progress bar, we can use either logo
- I created a GIF but when exporting it, it becomes grainy. but sending here the link just incase: https://drive.google.com/file/d/1__vep3_IXcS7xBuNM1TxHo937GsX243R/view?usp=sharing

## Considered
- [x] This proposal fits [company vision](https://github.com/colonistio/katan/blob/development/docs/company/company-values.md)
- [x] This proposal is impactful according to [Prioritizer Sheet](https://docs.google.com/spreadsheets/d/1A2qZ-KG4E2ma8TdnP_9LayMfnEfLVhmoM5_SgazXYHw/edit#gid=0)
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

Links:
Figma: https://www.figma.com/file/SysB628vRorzV7E9Pp9JuR/Colonist---(Sam)-File?node-id=1656%3A275464&t=3qGkvb1GYUSva1D8-1
GDrive: https://drive.google.com/file/d/1__vep3_IXcS7xBuNM1TxHo937GsX243R/view?usp=sharing

## Reviewers
@Mau-MD @demiculus @JuanRoman77

**Comment by Mau-MD** [comment]
Taking a look at other Discord Activities they all use a loading spinner (probably because it is technically more difficult to implement a loading bar as there is no way to know the progress of your app loading)

Also, I'm not a huge fan of the design, if you take a look at Gartics Phone. The loading screen looks really vivid. Can we have something similar to mobile (with the tiles and stuff) but made for a desktop screen?

![CleanShot 2023-04-08 at 10 32 33@2x](https://user-images.githubusercontent.com/74751751/230735099-e6a260d6-53cd-4361-834b-7d69317c9eba.png)

**Comment by Mau-MD** [comment]
@samgawaran

**Comment by Mau-MD** [comment]
Close issue?
