### ISSUE TITLE
Profile Page Submission #4 - Match History Screen Studies

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#43]
## Summary
- Created variations for the Match History screen, compatible that are compatible with the Overview screen studies in https://github.com/colonistio/design/issues/42
- Proposals are based on findings at  https://github.com/colonistio/design/issues/40

## Details
https://www.loom.com/share/9f1242bc71e847beba70217503806b13
## Previous Submissions

- https://github.com/colonistio/design/issues/42
- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/40

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [x] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [x] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [x] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [x] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
forgot to tag last night, 
@demiculus @JuanRoman77 @alperozgunyesil for review

**Comment by alperozgunyesil** [comment]
ah i didn't see this one, i am away from home & my computer. I'll run for your help ASAP!

**Comment by demiculus** [comment]
Nice, I like how you've provided lots of ideas 👍 

1. Removing duration & VP is the right choice. The main part should only show the important data. The question is what data is essential. 
2. We already talked about not going with status. 
3. Removing the info button is also the right choice
4. I like the opponents names writing instead of icons. Lets go with opponent name: https://colonist.io/profile/Demiculus
5. Game type & mode, good idea. But I think we should go with a single column which writes the `{{game mode}}` if non ranked and writes `Ranked + {{game mode}}` if ranked. That way we don't have to repeat unranked each time. But we might change the idea of writing ranked vs game mode later on. We'll see. 
6. You can continue with the designs. Show expanded version.

**Comment by JuanRoman77** [comment]
7. Remove `Points/game` (not useful since all game modes have different vp count so it doesn't provide any additional information), `Completed Games` (most players have +97/100, it's not useful either imo), and Time Spent (doesn't mean much since each game take a different time). Let's go with Wins, Win %, Karma, and Total Games.
8. Remove edit profile button, let's keep the top right drop down to edit stuff (username, avatar, color). 
9. Avatar shouldn't be so huge.
10. Why repeat avatar in /profile and in header profile?
11. Why repeat flag in /profile and in header profile?
12. Subscribers will have access to all expansions and game modes. So keep that in mind, it won't look as collectables for them.
13. Items should appear in their corresponding category, and display its name. 
14. Add an achievements section for league wins ("Season 12 winner - Bronze division" + avatar)
15. Add global and country ranking for Members
16. I feel like the side navigation bar takes a lot of real estate, in a page where a lot of content needs to be displayed. Even though it would be consistent with the rest of the pages, I'd rather go with something different for the profile, like this one https://i.imgur.com/U3kKfjr.png. I don't like any of the others, they are either too clogged or too bulky.
17. Search bar should appear next to the player's name and stats, that's the main info changing when searching for another user https://i.imgur.com/PTYoon3.png

**Comment by demiculus** [comment]
17. You can experiment search with not a search bar but just an icon wheres when clicked can expand into a search bar
