### ISSUE TITLE
Profile Page Submission #10 - Profile Tabs (Guest View)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#49]
## Summary
Collated all comments from previous submissions and created an initial prototype for the Guest View of the profile page.

## Details
https://www.loom.com/share/fe2ad1a674d74b32a797d5a9be9def9b

## Previous Submissions
- https://github.com/colonistio/design/issues/48
- https://github.com/colonistio/design/issues/47
- https://github.com/colonistio/design/issues/46
- https://github.com/colonistio/design/issues/45
- https://github.com/colonistio/design/issues/44
- https://github.com/colonistio/design/issues/43
- https://github.com/colonistio/design/issues/42
- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/40

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [x] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [x] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [x] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [x] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For Review:
@demiculus @JuanRoman77 @huaniebun @alperozgunyesil

**Comment by JuanRoman77** [comment]
1. Search bar doesn't work here. It makes the side nav inconsistent. I liked the previous location for the search bar, at the top right corner of the overview section, next to the players' name. That makes more sense.
2. Go with this https://i.imgur.com/Sm9TCwr.png I don't want to see countries or avatars, I want to know who I played against and click on their names to check their profiles.
3. Add the items' names as suggested before, otherwise it's just images that all look the same https://i.imgur.com/UY4elGd.png 
4. Don't make the avatars this big, 98% of the players don't have a store avatar. It looks pretty in the design, but it's not how it will look like after implementation. This page will look really bad if there are 20 white player_icon taking space. 
5. Add won/lost games, put the member thing elsewhere. I think that the stroke around the player avatar is enough (maybe add a small member icon in one of the avatar's corner https://i.imgur.com/vjciZVx.png).
6.

**Comment by samgawaran** [comment]
@JuanRoman77 before doing my next submissions, want to show you these first: these are for the profile-guest view:
![image](https://user-images.githubusercontent.com/90673012/169482610-7265fabe-8d6b-4cb9-90c9-35fa5ba76b4b.png)

- didn't add games lost, it would be shitty to look at if the player is a noob.
