### ISSUE TITLE
Profile Page Submission #13 - Profile Tabs Changes/Fixes

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#54]
## Summary
- Collated all of the comments/feedback given at https://github.com/colonistio/design/issues/51 and iterated on the design

## Details
![image](https://user-images.githubusercontent.com/90673012/170006947-66636dec-c5c2-45a6-8e47-9fce3aa1bc93.png)

1. Removed the `Add Friend` Icon and put in inside the `...` the button will now contain Add/Remove Friend, Block, Report
2. I agree with @alperozgunyesil, tabs are too colorful before so I created a basic color code without the gradient. Also removed some elements in the avatars for `Friends` 
3. Followed Juan's comment and changed stats to `Total Win/Lost` and `Win Rate` 
4. I did some few ideas here: https://github.com/colonistio/design/issues/55

Also added `Achievements` Tab here. I've shown the membership tab inside the Guest View for preview

## Previous Submissions
- https://github.com/colonistio/design/issues/51
- https://github.com/colonistio/design/issues/50
- https://github.com/colonistio/design/issues/49
- https://github.com/colonistio/design/issues/48
- https://github.com/colonistio/design/issues/47
- https://github.com/colonistio/design/issues/46
- https://github.com/colonistio/design/issues/45
- https://github.com/colonistio/design/issues/44
- https://github.com/colonistio/design/issues/43
- https://github.com/colonistio/design/issues/42
- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/40

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by JuanRoman77** [comment]
> 2. I agree with @alperozgunyesil, tabs are too colorful before so I created a basic color code without the gradient. Also removed some elements in the avatars for Friends


Disagree. We have other pages with side bar and the icons in there are colorful. We don't have icons with basic color code other than in the ingame help icons.
![image](https://user-images.githubusercontent.com/73320460/170129603-2c8a4543-d873-4bdd-a6a4-06f873ab3aa8.png)
![image](https://user-images.githubusercontent.com/73320460/170129668-0f1c2c50-041d-4afc-ba3c-7cb0ac141dd2.png)
![image](https://user-images.githubusercontent.com/73320460/170129719-9d00ff51-f7d3-49a6-aa50-010c448f9b92.png)

----

What about a down arrow (like profile https://i.imgur.com/AMKapKi.png) instead of **....**? For consistency. 

----

Remove brackets from (Global)

**Comment by samgawaran** [comment]
> What about a down arrow (like profile https://i.imgur.com/AMKapKi.png) instead of ....? For consistency.

Just checked, Facebook does this too. Yep, we can do this. Sending a new iteration later

**Comment by huaniebun** [comment]
Hi Sam, just looked through the different versions of Guest and Owner Profile Pages and here are my comments:
1.  agree with Juan that icons should be colourful to match the style with the rest of the site.
2.  search bar clutters the profile pages --> could consider shifting it to leaderboards instead (makes more sense to search for a player in that situation). With search bar in leaderboards, you will have space for:
  a. [guest profile] a clear add friend/unfriend and block button on the top right 
  b. [owner profile] button for edit profile/ 3 dots for profile options 
3. since owner and guest profiles have a similar layout for consistency, would be good to have some indication that you are looking at your own profile vs another player's --> can consider naming tab for 'Overview' as 'My Profile' for own profile and 'Profile Overview' for another player's (you may come up with better naming conventions than me)
4. why is the stroke around the avatar colourful? If it is to indicate membership, I think colour of the membership plan is enough - another icon to indicate membership plan clutters the avatar space.
5. Icon for 'Match history' is more for stats than history - can consider a more appropriate icon.

Will comment on the details of the player stats separately.

**Comment by samgawaran** [comment]
> search bar clutters the profile pages --> could consider shifting it to leaderboards instead

@JuanRoman77 given Huan's reasoning for this, I'd say we can also do this one, what do you think? do we have data that players use the search function in our current profile page?

**Comment by JuanRoman77** [comment]
> > search bar clutters the profile pages --> could consider shifting it to leaderboards instead
> 
> @JuanRoman77 given Huan's reasoning for this, I'd say we can also do this one, what do you think? do we have data that players use the search function in our current profile page?

No, having a search bar in the profile makes sense since 100% of the players have a profile. That's where they look for each other to compare stats, add as friends, check karma, etc.

**Comment by huaniebun** [comment]
@JuanRoman77 If the purpose for searching another person's profile is to compare stats, then it would be good to have the two profiles side by side than going back and forth between your profile and a friend's. It will be easier to see the comparison in the leaderboards compared to the profile page. (also depends on what kinds of stats players would like to compare with, and which page shows that) 

If it is to check karma or add friend, then a profile page would make sense (though they can click on the person's profile through leaderboards as well)

**Comment by JuanRoman77** [comment]
> though they can click on the person's profile through leaderboards as well

Yes, but most people won't use the leaderboards.

> it would be good to have the two profiles side by side than going back and forth between your profile and a friend's.

True, but there isn't enough space to do that 🤔 
Also it's not just for comparing purposes. People stalk others to gauge skill, even without checking their own numbers. If I see someone with +40% win ratio and 2k games played, I know they are good. No need to compare to my own numbers.
