### ISSUE TITLE
Profile Page Submission #15 - Profile Tabs (Guest View and Owner View) Iteration #3

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#57]
## Summary
Here are the current prototypes for the profile pages, added Player access points, Achievements tab (No screens yet) and improved all of the pages based on feedback/comments given

## Prototypes
Guest View
https://www.figma.com/proto/qoJZHxfBsMHtGRXNu5msuM/Colonist-UI%2FUX-Master-File?page-id=3245%3A57499&node-id=7386%3A365734&viewport=857%2C4514%2C0.25&scaling=contain&starting-point-node-id=7386%3A365734

Owner View
https://www.figma.com/proto/qoJZHxfBsMHtGRXNu5msuM/Colonist-UI%2FUX-Master-File?page-id=3245%3A57499&node-id=7386%3A363595&viewport=857%2C4514%2C0.25&scaling=contain&starting-point-node-id=7386%3A363595

## Previous Submissions
- https://github.com/colonistio/design/issues/55
- https://github.com/colonistio/design/issues/54
- https://github.com/colonistio/design/issues/51
- https://github.com/colonistio/design/issues/50
- https://github.com/colonistio/design/issues/49
- https://github.com/colonistio/design/issues/48
- https://github.com/colonistio/design/issues/47
- https://github.com/colonistio/design/issues/46
- https://github.com/colonistio/design/issues/45
- https://github.com/colonistio/design/issues/44
- https://github.com/colonistio/design/issues/43
- https://github.com/colonistio/design/issues/42
- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/40

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For Review:
@demiculus @JuanRoman77 @huaniebun @alperozgunyesil

note: 
- didn't add `game mode stats` on the overview yet. it's on a separate issue here: https://github.com/colonistio/design/issues/55

**Comment by JuanRoman77** [comment]
https://i.imgur.com/Si26hpg.png
1. Too big
2. Too big
3. Explore different UX
4. Cards too big

5. Add info icon for game details https://i.imgur.com/uefwF6h.png
6. Remove colons https://i.imgur.com/iWF1PEO.png
7. Players who own Membership will have access to all Maps and Expansions. If they cancel their Membership, they will see the items as collectables, otherwise the inventory will be full. Perhaps the parenthesis below Expansions could say "Membership - Access to all Expansions" or something like that https://i.imgur.com/eYYQn1N.png
8. Search box is too big. Reduce its size so it looks like the one in Leaderboards. Position should be the same as well. https://i.imgur.com/bYRr4dO.png
