### ISSUE TITLE
Profile Page Submission #24 - Profile Tab Updates + Prototype

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#75]
## Summary
Compiling current screenshots of the profile page as suggested by @demiculus, I also included a working, scrollable prototype as well.

## Prototype
https://www.figma.com/proto/qoJZHxfBsMHtGRXNu5msuM/Colonist-UI%2FUX-Master-File?page-id=3245%3A57499&node-id=7716%3A383102&viewport=5464%2C-792%2C0.25&scaling=scale-down&starting-point-node-id=7716%3A383102

Note:
You can click on the tabs to anchor you on that part of the page but the placement isn't accurate yet. new feature of Figma I'm still mastering

## Screens
Overview + Tab
![image](https://user-images.githubusercontent.com/90673012/171971924-2fbea205-9c4a-40f8-a0bd-a047b35348d4.png)
Status: still doing iterations here: https://github.com/colonistio/design/issues/73 & https://github.com/colonistio/design/issues/74

History
![image](https://user-images.githubusercontent.com/73320460/171986460-d1749fd3-b4b8-482a-8924-6324b643907f.png)
Status: Juan and I discussed making it left aligned, but for now we decided to make it center aligned. I'm in favor of left while Juan is in favor of centered. Other than that, this is finalized

Items
![image](https://user-images.githubusercontent.com/90673012/171972000-5afc6c36-371f-4c7a-a305-e079c33be1e1.png)
Status: Complete

Friends
![image](https://user-images.githubusercontent.com/90673012/171972019-d3514084-2583-4ad5-993b-f3bfd79542b4.png)
Status: Complete (low priority)

Membership
![image](https://user-images.githubusercontent.com/90673012/171972036-6fece256-d963-4717-8a1e-b3594f0e4888.png)
Status: Complete

## Related links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77 @huaniebun @alperozgunyesil @DyLightedCatan

**Comment by demiculus** [comment]
1. It shouldn't be all scrollable like store. Each page should be different.
  - Loading all of the data when the profile opens is not ideal, we don't want to load all the data each time
  - Having 2 vertical scrolls in each other is not a good experience. (main scroll + history, main scroll + friends)
@JuanRoman77 let me know if separate pages don't make sense for some reason. 
  - For the loading data we'd have to do lazy load
  - For the stacking vertical scrolls, I have no idea.. 
2. What are the medals?
3. What does the dropdown next to the flag do?
4. "My profile" change its name to "Stats"
5. @JuanRoman77 decide what should go inside "My Profile" and Sam should show those. We'll iterate on them as time goes by.
6. Do another iteration on Ranked, copy styles from other games
7. History, can you show me a left aligned & center aligned example?
8. History details, this line might not be needed. You can play around with the left & right side to decrease the amount of titles & lines.  https://i.imgur.com/TPPbG4l.png also might be better to left align game details, will make it easier to read. 
9. Items should be buyable from profile. For the ones that are grayed out, it should show coin amount and purchase button or both of them together
10. Friends, should show if they are currently playing in a game linking to the game
11. Membership, if they aren't member it should show that they can become one

Btw some of these are for viewing your own profile, some are viewing other peoples profile.
For example you need
Membership -> vieweing your own profile & not purchased
Membership -> vieweing your own profile & purchased
Membership -> vieweing another profile & not purchased
Membership -> vieweing another profile & purchased

Please show options like these for all the pages since they might be different.

**Comment by samgawaran** [comment]
> What are the medals?
Achievements the player had from last season ex. (Ranked #1 in home country) Juan and I had not talked about this much deeper though. 

> What does the dropdown next to the flag do?
Options where other players can add/block/report you. I'd just show it for the prototype but it's not present if you're viewing your own profile

> "My profile" change its name to "Stats"
I said [here](https://github.com/colonistio/design/issues/74#issuecomment-1146729515) that the word Stats is a bit general since `Ranked` and `History` shows stats too. But I can keep it as `Stats` for now since we can just easily change the name during development.

**Comment by JuanRoman77** [comment]
> It shouldn't be all scrollable like store. Each page should be different.

Agree. And Store shouldn't be scrollable either, we need to update that.

**Comment by demiculus** [comment]
> Achievements the player had from last season ex. (Ranked 1st in home country) Juan and I had not talked about this much deeper though.

You can remove the medals, we'll think about it in the achievement issue, not important atm

> Options where other players can add/block/report you. I'd just show it for the prototype but it's not present if you're viewing your own profile

Can you try icons for that? And lets see how it looks.

**Comment by JuanRoman77** [comment]
> You can remove the medals, we'll think about it in the achievement issue, not important atm

Ignore the medals, the idea is to use that space to display achievements. That's what the medals represent. When the profile is coded, there should be a container there to show achievements.
